### ISSUE TITLE
Modifier is passed to loading / error images

### ISSUE THREAD

**Issue by pepijntb** [skydoves/landscapist#104]
- glide:1.4.6 
- All devices
 
**Describe the Bug:**

It took some time to find out that the modifier was passed along to the placeholder and error images. This makes setting the padding a bit cumbersome. In my case the placeholder image was very small but this was due to the paddings being set twice.

**Expected Behavior:**

I would expect the placeholder and error image to be drawn inside the GlideImage box and the paddings in the modifier for this box to not be forwarded to the subimages.

**Comment by skydoves** [comment]
Hi @pepijntb, thank you for filing this issue.
Could you please also provide your code and results? Thanks!

**Comment by skydoves** [comment]
@pepijntb
You can use the patch version `1.4.7-SNAPSHOT` now and it will be included in the next release.
Thanks!
