### ISSUE TITLE
ClassCastExpetion and imageState problem

### ISSUE THREAD

**Issue by FVerhamme** [skydoves/landscapist#117]
I tried the library with Glide as described with a default placeholder an an error placeholder.
```
...
placeHolder = ImageBitmap.imageResource(R.drawable.ic_default_image),
...
```
The app crashes with the following error:
java.lang.ClassCastException: android.graphics.drawable.VectorDrawable cannot be cast to android.graphics.drawable.BitmapDrawable

Second:
If tried with state the given example shows the following:
```
GlideImage( // CoilImage, FrescoImage
  imageModel = imageUrl,
  // draw a resized image.
  success = { imageState ->
    imageState.imageBitmap?.let {
      Image(
        bitmap = it,
        modifier = Modifier.size(128.dp)
      )
    }
  },
```
But imageState will return a drawable. In this case how to convert this drawable to an BitmapImage to place it inside the Image( ?

Used Library Version: 1.5.0
Effected Devices: Android Emulator 12

**Comment by skydoves** [comment]
Hi @FVerhamme, sorry for the late response.

1. When you use a vector resource, you should use the `ImageVector` instead of the `ImageBitmap` as below:
```kotlin
ImageVector.vectorResource(id = R.drawable.ic_default_image)
```

2. You can use `rememberDrawablePainter` with the `drawable`.
```kotlin
  Image(
    painter = rememberDrawablePainter(drawable)
    ...
```

Thanks!
