### ISSUE TITLE
GlideImage wont load drawable image

### ISSUE THREAD

**Issue by thekingrenz23** [skydoves/landscapist#135]
**General Information:**
- Library Version [1.5.2]
- Affected Device(s) [All]
 
**Bug description:**

Loading a drawable image does not work
```
GlideImage(
   imageModel = ImageBitmap.imageResource(R.drawable.default_profile)
   ...
)
```

**Expected Behavior:**

Should load the drawable image

**Comment by skydoves** [comment]
Try this:

```kotlin
GlideImage(
   imageModel = R.drawable.default_profile
   ...
)
```

**Comment by thekingrenz23** [comment]
it works thanks
