### ISSUE TITLE
Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find landscapist-fresco-1.5.2.jar (com.github.skydoves:landscapist-fresco:1.5.2).

### ISSUE THREAD

**Issue by 474246820** [skydoves/landscapist#137]
**Please complete the following information:**
- Library Version [1.5.2]
- Affected Device(s) 
all
**Describe the Bug:**
Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find landscapist-fresco-1.5.1.jar (com.github.skydoves:landscapist-fresco:1.5.1).
**Expected Behavior:**
If this dependency is added, an error will be reported

**Comment by skydoves** [comment]
Please make sure your project includes the `mavenCentral()` and added the dependency below:

```gradle
implementation "com.github.skydoves:landscapist-fresco:1.5.2"
```

If you face the same issue, check out your Gradle build/cache systems.

Also, you can check out the artifact is released on maven central properly here - https://search.maven.org/artifact/com.github.skydoves/landscapist-fresco/1.5.2/aar
