### ISSUE TITLE
[Question] Local drawables

### ISSUE THREAD

**Issue by GuilhE** [skydoves/Landscapist#14]
I didn't find a way to load a local resources and apply the nice reveal animation, is it possible?
Thanks.

**Comment by skydoves** [comment]
Hi, can you explain more details about the local resources with some examples?

**Comment by GuilhE** [comment]
Instead of 
```
CoilImage(
  imageModel = imageUrl,
  contentScale = ContentScale.Crop,
  circularRevealedEnabled = true,
)
```
Something like:
```
CoilImage(
  imageModel = imageResource(R.drawable.my_local_drawable),
  contentScale = ContentScale.Crop,
  circularRevealedEnabled = true,
)
```

**Comment by skydoves** [comment]
Ah, that's very simple.

```kotlin
CoilImage(
  imageModel = R.drawable.my_local_drawable,
  contentScale = ContentScale.Crop,
  circularRevealedEnabled = true,
)
```

**Comment by GuilhE** [comment]
Thanks! 😅

**Comment by jagan999** [comment]
It is NOT the same issue. My issue is not about loading a drawable resource. That works fine. My issue is that I am unable to locate xyz.jpg file that is present on my local device under the system files directory
