### ISSUE TITLE
Coil.imageLoader is leaking

### ISSUE THREAD

**Issue by ichvandi** [skydoves/landscapist#146]
**Please complete the following information:**
- Library Version : v1.5.2
- Affected Device(s) : Android Emulator Pixel 4 API 32
 
**Describe the Bug:**

Coil.imageLoader is detected leaking by LeakCanary, when navigating to another screen

<img width="591" alt="image" src="https://user-images.githubusercontent.com/23291739/178128468-db127568-55da-4cf3-a620-4071407a06b3.png">

[Leak Canary Log](https://pastebin.com/X4LsM9e4)

Example Video
https://user-images.githubusercontent.com/23291739/178128450-5084f34f-1eb2-4f0c-8670-795325ebf2d8.mp4

**Expected Behavior:**

Not leaking

**Comment by skydoves** [comment]
Hey @ichvandi, 
I tested with version 1.5.3` with some projects including [DisnyCompose](https://github.com/skydoves/disneycompose), but I couldn't represent the memory leak issue. Could you expand on this more? I guess it seems like an internal issue of Coil.

**Comment by skydoves** [comment]
For now, will close this issue. If you feel this issue happened by this library, please re-open and discuss it here again. Thanks!
