### ISSUE TITLE
Blur effect on image  | applying transformation on glide view

### ISSUE THREAD

**Issue by RishiKrYML** [skydoves/landscapist#184]
**Is your feature request related to a problem?**
I have the requirement of showing different loading/error/success state in my composable.  I also need to apply blur effect (right now just this, for other people it could be some other effect ) for success image. 
 
**Describe the solution you'd like:**

I am not sure if there is already support of such in landscapist. 

If yes, then could u please help to know how it could be done.
if no, If feasible and worthwhile your time, please see what can be done here.

**Describe alternatives you've considered:**
 There is something like this which seems to be working.
https://stackoverflow.com/a/47262444/14034095

How do we apply transformation to GlideImage or such.
`Glide.with(context)
   .load(“YOUR IMAGE URL HERE”)
   .bitmapTransform(new BlurTransformation(context))
   .into(imageView);`

p.s. This is an awesome library, really helped me a lot. Thanks for this.

**Comment by skydoves** [comment]
Hi @RishiKrYML,
You can apply the blur effect by adding the `blur` method to your modifier.

```kotlin
  GlideImage(
    imageModel = { poster.image },
    modifier = Modifier.blur(20.dp)
)
```

Also, you can customize the loading/error/success with the [Custom Composables](https://github.com/skydoves/landscapist#custom-composables).

**Comment by RishiKrYML** [comment]
Hi @skydoves, 
That's the solution I tried but it looks to be working only in Android 12 and above.
Reference : https://stackoverflow.com/a/69224858/14034095

There are other messy ways to do like, 
1. Manually get drawable is success call back ->convert to bitmap -> apply transformation -> use output bitmap into compose view
2. Get a blur asset and show it as a overlay on top of the drawable, (resizing of asset in view would be needed if I am to use like staggered layout item )

I just wanted to see if there was way to get transformation applied easily in landscapist. Thanks.

**Comment by skydoves** [comment]
Hey @RishiKrYML here is the best solution:

1. Add the dependency below:

```groovy
  implementation 'jp.wasabeef:glide-transformations:4.3.0'
```

2. Set the `glideRequestType` and `requestBuilder` parameters like the below:

```kotlin
  GlideImage(
    imageModel = { poster.image },
    modifier = Modifier.aspectRatio(0.8f),
    glideRequestType = GlideRequestType.BITMAP,
    requestBuilder = {
      Glide.with(LocalContext.current)
        .applyDefaultRequestOptions(RequestOptions.bitmapTransform(BlurTransformation(25, 3)))
        .load(poster.image)
    },
    component = rememberImageComponent {
      +CircularRevealPlugin()
      +PalettePlugin { palette = it }
    },
    previewPlaceholder = R.drawable.poster
  )
```

The `glideRequestType` parameter is available since the version `2.0.2`. Thanks!

**Comment by skydoves** [comment]
Hey @RishiKrYML, since version `2.0.2` you can implement the blur effect with `BlurTransformationPlugin` in the `landscapist-transformation` package.

Check out the documentation for more details: https://github.com/skydoves/landscapist#transformation

**Comment by RishiKrYML** [comment]
Hi @skydoves,
Thank you for above quick response.

There is one more thing, 
If I use with 'success' callback , blur effect doesn't work. 
If I remove 'success' block blur effect works.

If it could easily solved then please let me know, If more work required we can leave if for now. (My requirement requirements requires to show shimmer while loading and then )

Below works.
`
 GlideImage(
            imageModel = { imageUrl.toString() },
            component = rememberImageComponent {
                +BlurTransformationPlugin(20)
            }
        )
`

Below doesn't work.
` GlideImage(
            imageModel = { imageUrl.toString() },
            success = { mImageBitmap ->
               // use this mImageBitMap into image view
            },
            component = rememberImageComponent {
                +BlurTransformationPlugin(20)
            }
        )`
