### ISSUE TITLE
No support for real target image sizes in glide

### ISSUE THREAD

**Issue by Forcharc** [skydoves/landscapist#188]
As I see in FlowCustomTarget it uses Target.SIZE_ORIGINAL, and not the real width/height
Which is bad, because it could potentially hold unnecessary big sizes of an image.

Do you have any plans on fixing that?

**Comment by skydoves** [comment]
Hey @Forcharc, thanks for reporting this. I'm planning to implement the custom target size in the next release.

**Comment by skydoves** [comment]
Hey @Forcharc, 

Since version **2.1.0**, you can set the request size of your image by giving `requestSize` property as seen in the below:

GlideImage(
  ..
  imageOptions = ImageOptions(requestSize = IntSize(800, 600)),
)

Thanks for the reporting!
