### ISSUE TITLE
Vector drawable support

### ISSUE THREAD

**Issue by itsyourapp** [skydoves/Landscapist#19]
Hi, I am new to Jetpack Compose so there may be an easy way to do this, but in any case, this may help users of your library. Can we use vector drawables for placeholder images?

**Comment by skydoves** [comment]
Hi, you can use a vector drawable for a placeholder like the below codes.

```kotlin
placeHolder = ImageBitmap.imageResource(R.drawable.ic_android)
```

**Comment by skydoves** [comment]
Hi, @itsyourapp 
Thanks for your issue! 
It will be supported in the next release. 👍

**Comment by skydoves** [comment]
New version [1.1.9](https://github.com/skydoves/Landscapist/releases/tag/1.1.9) has been released!

**Comment by itsyourapp** [comment]
@skydoves Great work! I am inspired by you and learning much from your codebases.
