### ISSUE TITLE
Blur transformation not working along with success callback

### ISSUE THREAD

**Issue by RishiKrYML** [skydoves/landscapist#191]
**Please complete the following information:**
- lib version 2.0.2.
- Samsung Galaxy s10 with Android 12 and emulator. [All devices]
 
**Describe the Bug:**
I had requested for blur transformation effect. You had provided BlurPlugins.  But blur effect does not work on work if I also using success callback .

Below works.
`GlideImage( imageModel = { imageUrl.toString() }, component = rememberImageComponent { +BlurTransformationPlugin(20) } )
`
Below doesn't work.
`GlideImage( imageModel = { imageUrl.toString() }, success = { mImageBitmap -> // use this mImageBitMap into image view }, component = rememberImageComponent { +BlurTransformationPlugin(20) } )`

**Expected Behavior:**
Blur transformation should be there in output of success callback.

I have some overlay to show on top of it which I am implementing inside success callback , hence requesting it the blur to be applied on input params of success callback.

**Comment by skydoves** [comment]
Hey @RishiKrYML, could you try the code below?

```kotlin
    success = {
      val imageBitmap = (it.data as Drawable).toBitmap().asImageBitmap()
      Image(
        painter = rememberBitmapPainter(
          imageBitmap = imageBitmap,
          imagePlugins = listOf(BlurTransformationPlugin())
        ), contentDescription = null
      )
    },
```

Essentially, `rememberBitmapPainter` is an internal API, but you can apply the blur transformation in this manner.
