### ISSUE TITLE
ContentScale when inside ConstraintLayout works differently on 2.0.3 and 2.1.0

### ISSUE THREAD

**Issue by ABIlunar** [skydoves/landscapist#202]
When GlideImage is used inside a ConstraintLayout on 2.1.0, and contentScale is set to "Crop", it behaves as "Fit" 

I have attached 2 images, where the only difference in code is the version bump from 2.0.3 to 2.1.0. 

2.0.3
<img width="281" alt="image" src="https://user-images.githubusercontent.com/97034926/202679842-1ccaf62c-b497-4a39-bb66-c041668550c5.png">

2.1.0
<img width="336" alt="image (1)" src="https://user-images.githubusercontent.com/97034926/202679855-8bf609e4-d69b-41ca-8662-ec84e5287bb5.png">

Code snippet to reproduce 
```

 ConstraintLayout(
            modifier = Modifier
                .clickable {
                    onClick()
                }
                .fillMaxWidth()
                .defaultMinSize(minHeight = 174.dp)
        ) {
            val (bottomRef, imageRef, backdropRef, topRightContentRef) = createRefs()

            GlideImage(
                imageModel = { imageUrl },
                modifier = Modifier.constrainAs(imageRef) {
                    top.linkTo(parent.top)
                    end.linkTo(parent.end)
                    bottom.linkTo(parent.bottom)
                    start.linkTo(parent.start)
                    width = Dimension.fillToConstraints
                    height = Dimension.fillToConstraints
                },
                imageOptions = ImageOptions(contentScale = ContentScale.Crop)
            )
        }




```

**Comment by skydoves** [comment]
Due to fixing the #128 issue, you should specify `fillMaxSize()` if you want to match it to the parent composable.

**Comment by OleksandrGrument** [comment]
Hello @skydoves, in version 2.1.1 still exist
