### ISSUE TITLE
Unexpected growing recompositions for FrescoImage

### ISSUE THREAD

**Issue by TemMax** [skydoves/landscapist#219]
- Library Version: 2.1.1
- Affected Device(s): all
 
Faced with a problem when FrescoImage does infinite recompositions when shown:
<img width="453" alt="image" src="https://user-images.githubusercontent.com/17501751/217512389-23880cc0-9a33-4a67-a8a3-4738bb3dd6c2.png">

It does not depend on size, placement, or other parameters of FrescoImage. You can reproduce it only with modifier and imageUrl params.

**Comment by skydoves** [comment]
Hi @TemMax, could you elaborate on this and something example?
