### ISSUE TITLE
Compose modifiers applied twice

### ISSUE THREAD

**Issue by dylan-mistplay** [skydoves/landscapist#224]
**Please complete the following information:**
- Library Version [e.g. v2.1.3]
- Affected Device(s) Google Pixel 3a with Android 12
 
**Describe the Bug:**
Calling `CoilImage()` with `modifier = Modifier.rotate(degrees = 90f)` causes the image to appear rotated 180 degrees. The preview displays the rotation as expected while the app shows double. Putting the `CoilImage()` in a `Box` and rotating the `Box` works as expected. 

Looking at the source code, it appears the same modifier is applied twice. Once on a `Box` inside `private fun CoilImage()`. Again on an `Image` inside `ImageOptions.LandscapistImage`. I'm not sure about a solution, but I hope that helps.

**Expected Behavior:**

Modifier only applies once. Preview matches app behavior.

**Comment by skydoves** [comment]
Hey @dylan-mistplay, this issue was fixed in the new release, version 2.1.4. Thanks for reporting the critical issue!
