### ISSUE TITLE
When we used from shape xml file for placeHolder app crashed.

### ISSUE THREAD

**Issue by parinexus** [skydoves/landscapist#235]
- Library Version v1.3.6
 
**Describe the Bug:**
We have to show placeHolder for myImage in compose. when we use shape xml files application crash.

my file:
`<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="oval">
    <solid android:color="@color/gray03"/>
</shape>`

**Comment by skydoves** [comment]
Hey, would you provide more context for this? And I wonder why you don't use Shape with Modifier in Jetpack Compose.

**Comment by parinexus** [comment]
> Hey, would you provide more context for this? And I wonder why you don't use Shape with Modifier in Jetpack Compose.

my code is this:
`GlideImage(
            modifier = Modifier.size(dimensionResource(id = R.dimen.profile_image_size)),
            imageModel = url ?: "",
            contentScale = ContentScale.Fit,
            circularReveal = CircularReveal(duration = 250),
            placeHolder = 
        )`
        
        I need use from that file in placeHolder.

**Comment by skydoves** [comment]
@parinexus You're using a too old version. Please try to update landscapist to `2.1.6` and check out the placeholder plugin: https://github.com/skydoves/landscapist#placeholderplugin

**Comment by skydoves** [comment]
For now, I will close this issue because there's nothing I can do from my side for version 1.x.
