### ISSUE TITLE
Avoid increasing apk size for preview images

### ISSUE THREAD

**Issue by AradiPatrik** [skydoves/landscapist#267]
**Is your feature request related to a problem?**

[As described here](https://stackoverflow.com/questions/76117182/using-jetpack-compose-landscapist-library-will-the-previewplaceholder-image-get/76118181#76118181) I want to have a way to have placeholder images for the Android Studio preview but at the same time not increase the final APK size.

**Describe the solution you'd like:**
I would like landscapist to have some way to have preview resources that get stripped away from the final APK

**Describe alternatives you've considered:**
If the final APK size really get's affected as of now, then the only alternative is not having images in the previews, which would slow down development.

Maybe this is handled already in that case I would suggest updating the documentation to explicitly say that the preview image won't affect the final apk size

**Comment by skydoves** [comment]
Hey @AradiPatrik, I don't think we have another solution for this issue because we can't use not included drawable for previews. I hope you can reduce apk size by replacing the preview image with mandatory resources, such as the application's luncher icon or something that you mush ship to customers.

**Comment by AradiPatrik** [comment]
Thanks for the quick response! I'm doing something similar right now. Hopefully in the future Jetpack Compose will add more support for image sample data (like they did with the avatar resources for xml previews)
