### ISSUE TITLE
GlideImage issue with parallax modifier inside a collapsing toolbar

### ISSUE THREAD

**Issue by dantist0** [skydoves/landscapist#280]
after update from 2.1.12 to 2.1.13 this code stop working

simple app to reproduce it https://github.com/dantist0/GlideImage_ReproduceProblem

Glide load, but don't show, but placeholder does

**Comment by skydoves** [comment]
The [demo app](https://github.com/skydoves/landscapist/tree/main/app) seems to work well from my side. Would you share your use cases or more contexts?

**Comment by dantist0** [comment]
I made simple app to reproduce this problem
https://github.com/dantist0/GlideImage_ReproduceProblem

**Comment by skydoves** [comment]
After I changed the GlideImage's modifier like the below, it works well:

```kotlin
modifier = Modifier
                    .background(Color.Cyan)
                    .fillMaxWidth()
                    .height(300.dp),
```

**Comment by skydoves** [comment]
Interesting. It works well if you just remove the `parallax(0.32f)` on your modifier.

**Comment by anton-begeima-okcupid** [comment]
I am seeing the same problem when I try to use GlideImage inside the custom `Layout()`. After `GlideImage` is measured and positioned in the `layout(width, height){....}` it is not loading. Is there any workaround for this issue?

**Comment by skydoves** [comment]
Hey @anton-begeima-okcupid, would you elaborate on this issue?

**Comment by anton-begeima-okcupid** [comment]
Sorry, turns out that there was an issue on my end. accompanist.HorizontalPager was somehow messing up my custom layout with the GlideImage. after switching to androidx.compose.foundation.pager.HorizontalPager everything works fine. I also tested the latest version of landscapist with a custom layout and it works fine. Sorry for the false alarm.

**Comment by skydoves** [comment]
I'm closing this issue now.
