### ISSUE TITLE
How to use Preload?

### ISSUE THREAD

**Issue by dkshin** [skydoves/landscapist#290]
I want to use glide's preload function.
How to use Preload?

**Comment by skydoves** [comment]
The image loading process is quite different in Jetpack Compose from the previous XML, so it's unavailable to use Glide's preload functions. Instead, you can reference #247. I'm going to think of supporting a thumbnail as a feature in future releases.

**Comment by skydoves** [comment]
Hey @dkshin, you can use the [thumbnail plugin](https://github.com/skydoves/landscapist#thumbnailplugin) in the latest version.
