### ISSUE TITLE
Image FitXYZ?

### ISSUE THREAD

**Issue by techker** [skydoves/landscapist#292]
**Please complete the following information:**
- Library Version [e.g. v1.0.0]
- Affected Device(s) [e.g. Samsung Galaxy s10 with Android 9.0]
 
**Describe the Bug:**

Using the CoilImage

I can't get the image to load full size in box?

CoilImage(
                imageModel = { dataRows.random() },
                component = rememberImageComponent {
                    // shows a shimmering effect when loading an image.
                    +ShimmerPlugin(
                        baseColor = background800,
                        highlightColor = shimmerHighLight
                    )
                },
                imageOptions = ImageOptions(
                    contentScale = ContentScale.FillWidth.  Tried all types
                    alignment = Alignment.Center                  tried to remove this.
                )
            )

Add a clear description about the problem.

**Expected Behavior:**

A clear description of what you expected to happen.

**Comment by skydoves** [comment]
You should pass Modifier properly.

```kotlin
modifier = Modifier.fillMaxSize()
```

**Comment by techker** [comment]
ah ok il try it thx
