### ISSUE TITLE
KMM & Compose Multiplatform support?

### ISSUE THREAD

**Issue by algoflows** [skydoves/landscapist#296]
Hey there, feature request coming up :)

KMM & Compose Multiplatform support

**Comment by akardas16** [comment]
is there any development on it?

**Comment by skydoves** [comment]
@algoflows @akardas16  Hey guys, great news. As Coil introduced supporting KMP on version 3.0.0, I'm also working on KMP support for landscapist. Stay tuned!

**Comment by skydoves** [comment]
Hey guys, since version 2.3.0, it has supported the Kotlin Multiplatform. 

```kotlin
sourceSets {
    val commonMain by getting {
        dependencies {
            implementation("com.github.skydoves:landscapist-coil3:$version")
        }
    }
}
```

Thanks for waiting for a long time!
