### ISSUE TITLE
Error for import of ImageOptions

### ISSUE THREAD

**Issue by wintren** [skydoves/landscapist#298]
**Please complete the following information:**
- BOM 2.2.0, -glide and -palette
- mobile versions irrelevant, build time issue
 
**Describe the Bug:**
If I try to add `com.skydoves.landscapist.ImageOptions` as an import I get an error message from the compiler:
```
error: cannot access ImageOptions
import com.skydoves.landscapist.ImageOptions;
                               ^
  bad class file: /Users/<User>/.gradle/caches/transforms-3/5f07ba76304c24c9b242209fe03128ba/transformed/landscapist-2.2.0-api.jar(/com/skydoves/landscapist/ImageOptions.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

**Expected Behavior:**

Import should not cause issue, or error should have information on how to solve it

**Comment by skydoves** [comment]
It seems that you need to clean your project and rebuild.

**Comment by skydoves** [comment]
Please comment if you still face the same issue after cleaning your project.

**Comment by wintren** [comment]
- I have now tried cleaning, rebuilding. And also invalidating cache (restart), cleaning, rebuilding.
- I have no dependency on Glide as it is
- I have updated so that I don't use latest alpha versions for compose, but use the same (latest) BOM for compose `2023.05.01`

The problem persists, same error log.

**Comment by skydoves** [comment]
Hmm, I think you should switch to using Java 17 for your project since Landscapist migrated to AGP 8.0.X and Java 17 in the recent versions.

**Comment by wintren** [comment]
I will have a look at it, upgrading kotlin and compose compiler while I am on it

**Comment by wintren** [comment]
Alright! It's working! Thank you for your help :D
I'm not very good at checking versions etc. so this is only a tip for semi-blind people like me. But maybe extract the compose version info from glide, coil, picasso and place it above all of them once - and add the java version there?

In either case, I have something that works now and I'm happy ^^
