### ISSUE TITLE
Infinite loading on image

### ISSUE THREAD

**Issue by Healiel** [skydoves/landscapist#302]
**Please complete the following information:**
- Library Version : v2.2.1
- Affected Device(s) : not a device specific

**Describe the Bug:**
When i use this code 

` var modifier = Modifier.fillMaxWidth()

        if (onClick != null) {
            modifier = modifier.clickable { onClick() }
        }

        GlideImage(
            imageModel = { image ?: bgImageId },
            requestOptions = {
                RequestOptions().diskCacheStrategy(DiskCacheStrategy.ALL)
            },
            imageOptions = ImageOptions(
                contentScale = ContentScale.Crop,
                alignment = Alignment.Center,
                alpha = if(blur) 0.8F else 1F
            ),
            onImageStateChanged = {
              Log.e("GLIDE","onImageStateChanged $it")
            },
            component = rememberImageComponent {
                +PlaceholderPlugin.Loading(painterResource(id = R.drawable.event_image))
                +PlaceholderPlugin.Failure(painterResource(id = R.drawable.event_image))
            },
            modifier = modifier
                .aspectRatio(1f)
        )`
, this work well for the first loading
![image](https://github.com/skydoves/landscapist/assets/86113365/a709a122-afa7-42e9-bd92-b59246603b0b)

but following call have an infinite loading showing only loading placeholder forever:

![image](https://github.com/skydoves/landscapist/assets/86113365/c5c86931-ebb6-475b-a5e4-695333043778)

image is always a working url (tried with ThumbnailPlugin and the image is shown  as a thumbnail correctly)
Add a clear description about the problem.

**Expected Behavior:**

always load the image and finish loading with an error or a success

**Comment by skydoves** [comment]
@Healiel Thanks for reporting this issue. Would you share your use case with me? Do you load an image inside a lazy list or something? I'm wondering what's the recomposition flow with the landscapist.

**Comment by skydoves** [comment]
Landscapist `2.2.2` has been released. Would you try to build with this?

**Comment by Healiel** [comment]
@skydoves Thanks for the reply. There is no lazylist or things like that, only Box and one scrollable collumn.

Version 2.2.2 did not correct it. 

While i was trying to find the "reason" of the bug, i found that it should come from "Modifier.clickable", as removing it 'solved ' the issue

**Comment by skydoves** [comment]
@Healiel Thanks for your investigation. Hmm, this is interesting. If you build the demo app with tweaking the samples like the one below, it doesn't make any issues.

```kotlin
@Composable
private fun SelectedPoster(
  poster: Poster,
  onClick: (() -> Unit)? = null,
) {
  var palette by rememberPaletteState(null)

  GlideImage(
    imageModel = { poster.image },
    modifier = Modifier
      .aspectRatio(0.8f)
      .clickable { onClick?.invoke() },
    component = rememberImageComponent {
      +PlaceholderPlugin.Loading(painterResource(id = R.drawable.ic_android))
      +PlaceholderPlugin.Failure(painterResource(id = R.drawable.ic_android))
      +CircularRevealPlugin()
      +PalettePlugin { palette = it }
    },
    previewPlaceholder = R.drawable.poster,
  )

..
```

**Comment by Healiel** [comment]
@skydoves 
i Found the problem : 

Url was coming from a MutableStateFlow "item" from room database, 
In the composant where i show glide component, i was updating  "item".
if "item" didn't change and onClick was using information from item, glide was stuck in infinite loading.

I found a fix by cleaning "item" (to value = null) before loading "item" and glide component.

I don't know if it's a problem from mutableStateFlow, glide or me

**Comment by skydoves** [comment]
It sounds like this recomposition issue. Anyway happy to hear that you found the issue. I'm closing this issue now.
