### ISSUE TITLE
Jetpack compose animations not working properly on Glide

### ISSUE THREAD

**Issue by JimmyMantilla** [skydoves/landscapist#307]
**Please complete the following information:**
- Library Version [e.g. v1.0.0]
implementation "com.github.skydoves:landscapist-glide:2.2.2"

- Affected Device(s) [e.g. Samsung Galaxy s10 with Android 9.0]
- Google pixel 4xl android 13
 
**Describe the Bug:**

im triying to implement an infinite color animation on a drawable loaded with glide, but in testing the animation looks pretty bad, like a damaged light bulb, when i test it with normal image compose objetc is smooth and works fine, but with this library is too buggy

here is the animation code: 

val transition = rememberInfiniteTransition()
            val animationcolor by transition.animateColor(
                initialValue = Color.White,
                targetValue = Color.LightGray,
                animationSpec = infiniteRepeatable(
                    animation = tween(700, easing = LinearEasing), repeatMode = RepeatMode.Reverse
                )
            )

the call to the Glide image:

Glide(img = Img , color = animationcolor, modifier = imageModifier)

Glide image:
@Composable
    fun Glide(img: Int, color: Color, modifier: Modifier){
    GlideImage(
        imageModel = { img },
        modifier = modifier,
        requestBuilder = {
            Glide
                .with(LocalView.current)
                .asBitmap()
                .apply(RequestOptions().diskCacheStrategy(DiskCacheStrategy.ALL))
        },
        imageOptions = ImageOptions(
            contentScale = ContentScale.FillBounds,
            alignment = Alignment.Center,
            colorFilter = ColorFilter.tint(color = color)
        ),
        previewPlaceholder = R.drawable.img,
    )
}

Add a clear description about the problem.

**Expected Behavior:**

A clear description of what you expected to happen.

**Comment by skydoves** [comment]
Hey @JimmyMantilla, can you give it `colorFilter` instead?

```kotlin
imageOptions = ImageOptions(colorFilter = ..),
```

**Comment by JimmyMantilla** [comment]
I need to put it with the .Tint otherwise it won't receive the color parameters, I've tried the experimental API of glide and it's working great, I will upload a video of the animation

**Comment by JimmyMantilla** [comment]
https://github.com/skydoves/landscapist/assets/62487359/3bd58542-7fe5-410f-a6c3-7981c3a40142

**Comment by skydoves** [comment]
@JimmyMantilla I'm wondering what if you implement the `success` lambda like the example below?

```kotlin
  GlideImage(
    imageModel = { poster.image },
    modifier = Modifier.aspectRatio(0.8f),
    component = rememberImageComponent {
      +CircularRevealPlugin()
      +PalettePlugin { palette = it }
    },
    success = { _, painter ->
      Image(
        painter = painter,
        contentDescription = null,
        colorFilter = ColorFilter.tint(animationcolor)
      )
    },
    previewPlaceholder = R.drawable.poster,
  )
```

**Comment by skydoves** [comment]
I will close this issue for now, please let me know or reopen this issue if you still face the same problem.
