### ISSUE TITLE
after upgrading to 2.2.3, weird compiler error...

### ISSUE THREAD

**Issue by LilMoke** [skydoves/landscapist#311]
So. I upgraded to version 2.2.3 and I changed my kotlin version to 1.9.0 and compose comppiler to 1.5.0 but I am getting this error during compile:

`/.gradle/caches/transforms-3/5142eadfa7eb9d79e54e9474f151d136/transformed/landscapist-animation-2.2.3/jars/classes.jar!/META-INF/landscapist-animation_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
`

Can you point me I a direction to correct where I can look to figure out what I have wrong with my build?

Its strange because it say it is expecting 1.7.1

**Comment by skydoves** [comment]
Hey @LilMoke, do you use Java 17 on your project?

**Comment by LilMoke** [comment]
We use Java 16, why do you ask?

**Comment by skydoves** [comment]
Landscapist requires Java 17 since version 2.1.18, so you need to update your Java version to 17 to use Landscapist 2.2.3.

**Comment by LilMoke** [comment]
Excellent, I will upgrade to 17, thank you for the clarification. After the change to 17 I will report her if I still have any issue.  I am closing this ticket for now.
