### ISSUE TITLE
[Doc Improvement] Add Compose version being used in library

### ISSUE THREAD

**Issue by jsericksk** [skydoves/landscapist#326]
I think it would be interesting to add directly to the README/docs a quick guide to the Compose version used in the library version, just like it is done in [Accompanist](https://github.com/google/accompanist#compose-versions). Looking at releases it is sometimes not clear which version of Compose is being used.

![screenshot](https://github.com/skydoves/landscapist/assets/36176569/ac3dd3dc-848f-4c97-8049-0f8d80a2e2c1)

**Comment by skydoves** [comment]
Hey @jsericksk, this is a really great point. Let me improve the docs when I have a moment soon. Thank you!

**Comment by skydoves** [comment]
@jsericksk The version map documentation has been added: https://skydoves.github.io/landscapist/version-map/

I hope this works well for you. Thanks for reporting this issue!
