### ISSUE TITLE
Update Glide version to 4.16.0

### ISSUE THREAD

**Issue by AradiPatrik** [skydoves/landscapist#329]
**Is your feature request related to a problem?**

Glide supposedly made some compose performance improvements under the hood so it might be useful

**Describe the solution you'd like:**

Update Glide version to 4.16.0

**Describe alternatives you've considered:**

4.15.1 is still ok, but I think we should keep up with the new versions

**Comment by skydoves** [comment]
@AradiPatrik Thanks for raising this issue. I will update the version and it will be contained in the next release today. Thanks!

**Comment by skydoves** [comment]
2.2.8 has been released.
