### ISSUE TITLE
Coil Animated Gif/WebP Config

### ISSUE THREAD

**Issue by MajidArabi** [skydoves/landscapist#335]
hi. I think the animated config doesn't correct and must be setup in this way:

    val context = LocalContext.current
    val imageLoader = ImageLoader.Builder(context)
        .components {
            if (Build.VERSION.SDK_INT >= 28) {
                add(ImageDecoderDecoder.Factory())
            } else {
                add(GifDecoder.Factory())
            }
        }.build()

    CoilImage(
        modifier = modifier,
        imageModel = { image },
        imageLoader = { imageLoader }
    )

**Comment by skydoves** [comment]
Hey @MajidArabi, thanks for sharing these changes. I will update the docs as you suggested.

**Comment by skydoves** [comment]
Updated.

**Comment by MajidArabi** [comment]
thanks for your attention.
but the `componentRegistry {  }` function must be repleced with `components { }` function.

IDE Message:
Using 'componentRegistry(coil.ComponentRegistry.Builder.() -> Unit): coil.ImageLoader.Builder' is an error. Replace with 'components'.
