### ISSUE TITLE
Glide ColorFilter

### ISSUE THREAD

**Issue by GuillaumeBourge** [skydoves/landscapist#365]
- Library Version 2.2.10
- Xiaomi 11 lite 5G with Android 12.0

I am using colorFilter on my Glide Image, it is working great until state change and make recomposition of the view.

For example, i have a composable text not related to my Glide Image (with colorFilter apply), if the text change the whole view will be recomposed (with flickering effect).
If i remove the colorFilter, it works smoothly and recompose only the text.

Flickering : 
```
Column {
        GlideImage(
                imageModel = { game.illustration },
                imageOptions = ImageOptions(
                            colorFilter = ColorFilter.colorMatrix(a.value)
                        )
        )
        
        Text(text = "Time left: $timeLeft")
}
```

I try with GlideImage from Glide library beta01 and it works smoothly too.

Working : 
```
Column {
        GlideImage(
                model =  game.illustration ,
                colorFilter = ColorFilter.colorMatrix(colorMatrix),
                contentDescription = "game",
        )
        
        Text(text = "Time left: $timeLeft")
}

```

**Comment by skydoves** [comment]
Hey @GuillaumeBourge, I wondering if it works with the code below:

```kotlin
  imageOptions = ImageOptions(
     colorFilter = ColorFilter.colorMatrix(a.value),
     testTag = game.illustration
 )
```

**Comment by skydoves** [comment]
FYI, @GuillaumeBourge, I just tested with the demo code by tweaking the `MainPosters.kt` file like the below:

```kotlin
  var title by remember { mutableStateOf("") }

  LaunchedEffect(Unit) {
    var aa = 0
    while (true) {
      aa++
      title = "title: $aa"
      delay(500)
    }
  }

  GlideImage(
    imageModel = { poster.image },
    modifier = Modifier.aspectRatio(0.8f),
    component = rememberImageComponent {
      +CircularRevealPlugin()
      +PalettePlugin { palette = it }
    },
    imageOptions = ImageOptions(colorFilter = ColorFilter.tint(Color.Cyan)),
    previewPlaceholder = R.drawable.poster,
  )

  Text(
    text = title,
    style = MaterialTheme.typography.h2,
    textAlign = TextAlign.Center,
    modifier = Modifier.padding(8.dp),
  )
```

The result is like so:

![2023-11-08 18 13 16](https://github.com/skydoves/landscapist/assets/24237865/7a27e93f-0e21-4a6e-bc2b-e47690f22b93)

I think your code `a.value`, which seems like a `State`, might make a donut-hole and keep creating useless recomposition scope.

**Comment by GuillaumeBourge** [comment]
Hello,
Thanks for your answers ! :)
Yes in the example copied the colorMatrix is a state but even if not i got the issue :
```
val colorMatrix = ColorMatrix()
        if (!game.status.locked) {
            colorMatrix.setToSaturation(0f)
        }
Column {
        GlideImage(
                imageModel = { game.illustration },
                imageOptions = ImageOptions(
                            colorFilter = ColorFilter.colorMatrix(a.value)
                        )
        )
        
        Text(text = "Time left: $timeLeft")
}

```

However i try the _remember_ on the ImageOption and it seems to work ! :)

**Comment by skydoves** [comment]
@GuillaumeBourge I'm happy to hear my suggestion works well! I'm closing this issue, then.
