### ISSUE TITLE
Reload Image If Failed

### ISSUE THREAD

**Issue by Micoder-dev** [skydoves/landscapist#373]
Glide Image: In the current implementation, there is a need to reload an image iteratively until successful loading. The provided URL is confirmed to be correct; however, intermittent failures are attributed to the extended loading time caused by the large image size. Requesting a solution or guidance on implementing a retry mechanism to overcome these intermittent loading failures.

**Comment by skydoves** [comment]
Hey @Micoder-dev, I hope this solution works for now.

```kotlin
  var imageOption by remember {
    mutableStateOf(
      ImageOptions(testTag = "")
    )
  }

  GlideImage(
    imageModel = { poster.image },
    modifier = Modifier.aspectRatio(0.8f),
    component = rememberImageComponent {
      +CircularRevealPlugin()
      +PalettePlugin { palette = it }
    },
    onImageStateChanged = {
      if (it is GlideImageState.Failure) {
        imageOption = ImageOptions(testTag = System.currentTimeMillis().toString())
      }
    },
    previewPlaceholder = R.drawable.poster,
  )
```
