### ISSUE TITLE
CoilImage is now not found in latest coil library

### ISSUE THREAD

**Issue by jayeshindianic** [skydoves/Landscapist#38]
```
// Coil
    implementation 'io.coil-kt:coil:1.3.1'
    implementation 'com.google.accompanist:accompanist-coil:0.15.0'
```

now in latest version, all parameter(option) are changed, ever name also change
you need to update readme file for coil.

**Comment by skydoves** [comment]
I think you are misunderstanding about this library.
You should add the below dependency instead of the above them.

```gradle
implementation "com.github.skydoves:landscapist-coil:1.3.1"
```
