### ISSUE TITLE
How to pause/resume webp animation?

### ISSUE THREAD

**Issue by rantianhua** [skydoves/landscapist#398]
**Is your feature request related to a problem?**

The following example shown us how to play an animation webp:

```
FrescoWebImage(
  controllerBuilder = {
      Fresco.newDraweeControllerBuilder()
          .setUri(poster.gif) // GIF or Webp image url.
          .setAutoPlayAnimations(true)
  },
  modifier = Modifier
    .fillMaxWidth()
    .height(300.dp)
)
```

Now I want to control the animation to pause/resume or start/stop the animation. I can make the parameter of setAutoPlayAnimations to be a `remember` field, however, FrescoWebImage will dismiss and show again, which is not smooth.

**Describe the solution you'd like:**

Provide a parameter to pause/resume the animation.

**Comment by skydoves** [comment]
Hey @rantianhua, I believe you can pause and restart the animatable by adding this to your builder:

```kotlin
.setControllerListener(object : BaseControllerListener<ImageInfo>() {
    override fun onFinalImageSet(id: String?, imageInfo: ImageInfo?, animatable: Animatable?) {
      animatable?.stop()
      animatable?.start()
    }
  } 
```

**Comment by rantianhua** [comment]
@skydoves I tried this one, the webp won't be shown anymore if I do this

**Comment by rantianhua** [comment]
@skydoves I tried again and it worked, thanks

**Comment by skydoves** [comment]
@rantianhua Happy to hear that!
