### ISSUE TITLE
minSdkVersion 21 cannot be smaller than version 24 and duplicate classes

### ISSUE THREAD

**Issue by ilyasshafigin** [skydoves/landscapist#430]
Library: com.github.skydoves:landscapist-palette-android
Library Version: v2.3.0
 
**Describe the Bug:**

On my project minSdk = 21.
Uses:
 - `com.github.skydoves:landscapist-palette:2.3.0`
 - `androidx.palette:palette:1.0.0`

Errors occur during compilation:
1. `Duplicate class androidx.palette.graphics.Palette found in modules androidx-palette-debug-runtime (com.kmpalette:androidx-palette-android-debug:2.2.0) and palette-1.0.0-runtime (androidx.palette:palette:1.0.0)`.
2. `Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 24 declared in library [com.github.skydoves:landscapist-palette-android:2.3.0] [...]/landscapist-palette-release/AndroidManifest.xml as the library might be using APIs not available in 21`

**Solution:**

1. Please update the kmpalette library to at least verison [3.0.0](https://github.com/jordond/kmpalette/releases/tag/3.0.0) (there fixed the problem with duplicate classes and minSdk)
2. And down to 21 minSdk in the landscapist-palette

**Comment by skydoves** [comment]
Hey, @ilyasshafigin, thanks for reporting this issue! This issue has been fixed in the new release, 2.3.1.
