### ISSUE TITLE
com.kmpalette.palette.graphics.Palette -> androidx.palette.graphics.Palette

### ISSUE THREAD

**Issue by jaredsburrows** [skydoves/landscapist#468]
**Describe the Bug:**

Can we use the official Android X version of Palette?

**Expected Behavior:**

It looks like the normal Android X version should handle the current use cases.

**Comment by skydoves** [comment]
Hey @jaredsburrows, since Landscapist is developed with KMP support by default, I'm eagerly anticipating the official AndroidX Palette's KMP support. I will re-open this issue and let you know once the official AndroidX Palette supports KMP.
