### ISSUE TITLE
Asking for intrinsic measurements of SubcomposeLayout layouts is not supported.

### ISSUE THREAD

**Issue by KwonDae** [skydoves/landscapist#482]
**Please complete the following information:**
- Library Version : 2.3.3
- Affected Device(s) : Samsung Galaxy Fold3 with Android 14.0
 
**Describe the Bug:**
```kotlin
Scaffold {
   Column {
      TabRow {
         Tab {
            LazyColumn {
                GlideImage
            ...
```

I'm using as above structure. 
When I use `GlideImage` inside `TabRow`, the following error occurs,

```
java.lang.IllegalStateException: Asking for intrinsic measurements of SubcomposeLayout layouts is not supported. 
This includes components that are built on top of SubcomposeLayout, such as lazy lists, BoxWithConstraints, TabRow, etc. To mitigate this:
 
- if intrinsic measurements are used to achieve 'match parent' sizing, 
consider replacing the parent of the component with a custom layout which controls the order in which children are measured, 
making intrinsic measurement not needed

- adding a size modifier to the component, in order to fast return the queried intrinsic measurement.
```

It is said that it does not support intrinsic measurements behavior inside components such as `TabRow` using `SubcomposeLayout`.

```kotlin
@Composable
fun TabRow(
    selectedTabIndex: Int,
    modifier: Modifier = Modifier,
    containerColor: Color = TabRowDefaults.primaryContainerColor,
    contentColor: Color = TabRowDefaults.primaryContentColor,
    indicator: @Composable (tabPositions: List<TabPosition>) -> Unit = @Composable { tabPositions ->
        if (selectedTabIndex < tabPositions.size) {
            TabRowDefaults.SecondaryIndicator(
                Modifier.tabIndicatorOffset(tabPositions[selectedTabIndex])
            )
        }
    },
    divider: @Composable () -> Unit = @Composable {
        HorizontalDivider()
    },
    tabs: @Composable () -> Unit
) {
    TabRowWithSubcomposeImpl(modifier, containerColor, contentColor, indicator, divider, tabs)
}
```
Is it possible that the contents of the `ImageLoad` are using `BoxWithConstraintsScope` internally in the process of calling the `ImageLoad` function in `private fun GlideImage`?

```kotlin
@Composable
public fun <T : Any> ImageLoad(
  recomposeKey: T?,
  executeImageRequest: suspend () -> Flow<ImageLoadState>,
  modifier: Modifier = Modifier,
  imageOptions: ImageOptions,
  constrainable: Constrainable? = null,
  content: @Composable BoxWithConstraintsScope.(imageState: ImageLoadState) -> Unit,
) {
```

<img width="1828" alt="image" src="https://github.com/skydoves/landscapist/assets/33443660/52292694-52ec-43d2-91c2-42e9cbcaef54">

**Comment by skydoves** [comment]
Hey @KwonDae, I believe you'll be able to resolve this issue by wrapping your `GlideImage` with a `Box` Composable, as demonstrated in the code below:

```kotlin
Box(modifier = Modifier.size(56.dp)) {
          GlideImage(..)
}
```

**Comment by KwonDae** [comment]
Should I use fixed size in parent composable of GlideImage?

```kotlin
    FlowRow(
        modifier = modifier.fillMaxWidth(),
        maxItemsInEachRow = 2,
    ) {
        items.forEach {
            ImageItem(
                item = it,
                modifier = Modifier.weight(0.5f)
            )
        }
    }
```

I use GlideImage within Modifier.weight

**Comment by skydoves** [comment]
Hi @KwonDae, you actually don't need to use `FlowRow` if you want to maintain the same width for each item as half the size. Instead, you can utilize `LazyVerticalGrid`.

```kotlin
LazyVerticalGrid(
      modifier = Modifier.fillMaxWidth(),
      columns = GridCells.Fixed(2)
) {
```

**Comment by KwonDae** [comment]
Hi @skydoves, Thanks to you, I was able to solve the Issue.
I'm more curious to see how coil render image without that issue in `FlowRow`. I find AsyncImage [using SizeResolver](https://github.com/coil-kt/coil/blob/main/coil-compose-core/src/commonMain/kotlin/coil3/compose/AsyncImage.kt#L178) with [ConstraintSizeResolver](https://github.com/coil-kt/coil/blob/main/coil-compose-core/src/commonMain/kotlin/coil3/compose/internal/ConstraintsSizeResolver.kt). 
Has it something to do with above issue?

GlideImage render content within [BoxWithConstraintsScope](https://github.com/skydoves/landscapist/blob/main/landscapist/src/commonMain/kotlin/com/skydoves/landscapist/ImageLoad.kt#L66),
AsyncImage use Layout with ConstraintsSizeResolver?

**Comment by skydoves** [comment]
Hey @KwonDae, Landscapist uses [SizeResolver](https://github.com/skydoves/landscapist/blob/main/coil/src/main/kotlin/com/skydoves/landscapist/coil/ConstraintsSizeResolver.kt) to request pre-computed image sizes before rendering. The reason for adopting [BoxWithConstraints](https://developer.android.com/reference/kotlin/androidx/compose/foundation/layout/BoxWithConstraintsScope) is to limit content sizes and support match-parent functionality. This is achieved by leveraging the properties of `SubComposeLayout`, which delegates incoming parent constraints, making it easier to implement match-parent features.

On the other hand, Landscapist offers other image libraries, such as Glide and Fresco, but they don't yet provide features similar to `SizeResolver`. Therefore, I need to find a better way to support all of them. This is important because `BoxWithConstraints` incurs slightly higher overhead compared to a regular `Box`.

**Comment by galisamas** [comment]
Hey, I have a case, where I have to support `match_parent` behavior for a single image. Are there any other solutions to avoid setting specific size values? The error says to "consider replacing the parent of the component with a custom layout which controls the order in which children are measured, making intrinsic measurement not needed". Have you considered supporting this for the Glide version of the library?
