### ISSUE TITLE
FrescoWebImage is cropped, no matter what ContentScale type is used

### ISSUE THREAD

**Issue by MiniEmerald** [skydoves/landscapist#502]
Hi, I encountered an issue with the library.

**Please complete the following information:**
- Library Version
com.github.skydoves:landscapist-fresco v2.3.4
com.github.skydoves:landscapist-fresco-websupport v2.3.4

- Affected Device(s)
All? (Tested on the Android Studio Emulator from API 24 to 35/VanillaIceCream, on a tablet, and on a phone)
 
**Describe the Bug:**

Content of a FrescoWebImage is cropped, no matter what ContentScale type is passed to the FrescoWebImage

Happens for both still and animated images

**Expected Behavior:**

FrescoWebImage image scaling behaves according to the ContentScale used

**Example with screenshot**
```kotlin
val url = "https://download.blender.org/branding/blender_logo_socket.png"

FrescoWebImage(
    controllerBuilder = {
        Fresco.newDraweeControllerBuilder().setUri(url)
    },
    contentScale = ContentScale.Fit,
    modifier = Modifier.fillMaxWidth()
)
```

![Screenshot_20240619_231151](https://github.com/skydoves/landscapist/assets/41841579/dc3e7ce9-88d3-4465-a4b1-794f06e33c87)

**Comment by skydoves** [comment]
Hey @MiniEmerald, thank you for reporting this issue. It has been fixed on the new release, 2.3.5.
