### ISSUE TITLE
Support for ktor 3.0.0-rc-1 or 3.0.0

### ISSUE THREAD

**Issue by piashcse** [skydoves/landscapist#554]
Would you please add support for ktor 3.0.0-rc-1. When I use kotr 3.0.0-rc-1  in my kotlin multiplatform project, the image is not loading yet.

**Comment by skydoves** [comment]
Hey @piashcse, landscapist is already using 3.0.0-rc-1, which platform didn't load image?

**Comment by piashcse** [comment]
Hi @skydoves thanks for your reply 

I have updated ktor-3.0.0-rc-1 in my kmp-movie multiplatform project but image is not loading most of the case  for updated one. I have given the PR link for reference and images before update and after update 

![Simulator Screenshot - iPhone 16 Pro - 2024-09-23 at 23 19 15](https://github.com/user-attachments/assets/57a7ae3b-7c9e-40ab-b6b0-c39b4261b399)

![Simulator Screenshot - iPhone 16 Pro - 2024-09-23 at 23 19 53](https://github.com/user-attachments/assets/10859b37-5e16-448f-b1a5-eeecdc7a63e0)



Ref: https://github.com/piashcse/kmp-movie/pull/4/files

**Comment by skydoves** [comment]
Hey @piashcse, have you ever tried with adding the `KtorNetworkFetcherFactory` like the code below?

https://github.com/skydoves/landscapist/blob/main/app/src/main/kotlin/com/github/skydoves/landscapistdemo/App.kt#L52

**Comment by skydoves** [comment]
Hey @piashcse, 2.4.0 has been released, and I just checked it works well from my side.

**Comment by piashcse** [comment]
@skydoves Thanks for the nice support its working fine now. I also added web support as well 
![Screenshot 2024-09-25 at 12 01 37 AM](https://github.com/user-attachments/assets/cdc277bc-404a-4e09-9c56-5a59f29b10ca)
