### ISSUE TITLE
Unable to load an image file using file:///<location on disk>

### ISSUE THREAD

**Issue by jagan999** [skydoves/Landscapist#57]
**Please complete the following information:**
- Library Version 1.3.6
- Affected Device(s) OnePlus 7t with Android 11
 
I've tried this snippet for loading a JPG image that's stored in my files directory. I have verified that this file exists locally on the device. I have tried load with the File object, the Uri and it still doesn't load the image
It fails to load the resource

                                    GlideImage(
                                        imageModel = <full path string to the local JPG file>,
                                        requestBuilder = Glide.with(LocalContext.current).load(File(<full path string to the local JPG file>))
                                    )

**Comment by skydoves** [comment]
Hi, is this issue is related to this library or [request formatting issue](https://stackoverflow.com/questions/32332003/glide-load-local-image-by-uri)?
Could you check please it is working correctly in general Glide request? 

```kotlin
Glide.with(context)
  .load( <full path string to the local JPG file>)
  .into(imageView)
```

Also, this issue could be affected by external storage permission.

**Comment by jagan999** [comment]
I have tried this as explained above. External storage permission is not the issue since I am only using internal files dir that does not need any permission. I have also tried wrapping ImageView inside AndroidView of Jetpack Compose and have the same issue.

**Comment by skydoves** [comment]
>I have also tried wrapping ImageView inside AndroidView of Jetpack Compose and have the same issue.

Then I think this issue is related to [Glide](https://github.com/bumptech/glide), not this library.
