### ISSUE TITLE
Wasm Cors error

### ISSUE THREAD

**Issue by carbaj03** [skydoves/landscapist#577]
landscapist-coil3 2.4.0

`Access to fetch at 'https://s.....5524408624459885.jpg' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

I cannot load images in my Wasm project; I get the error above, and I don't know if it is a problem with the library or my application.

**Comment by skydoves** [comment]
I don't think this is related to the library issue. 

The error you're encountering is related to **CORS (Cross-Origin Resource Sharing)**. This policy is enforced by web browsers to prevent scripts on a web page from making requests to a different domain (origin) than the one that served the web page, unless the server explicitly allows it.

Here's a breakdown of the issue:

- **Cause**: You're trying to fetch a resource (`https://...jpg`) from a different origin (a different domain, protocol, or port) than your web application (`http://localhost:8080`), and the server serving the image doesn't allow this by default. This is a CORS restriction.

- **Missing Header**: The error specifically mentions that the resource doesn’t include the `Access-Control-Allow-Origin` header in its response, which is required for cross-origin requests to be successful. This header tells the browser whether or not it’s permitted to fetch resources from this other origin.

- **Opaque Response**: An opaque response is a type of response where you can't read the contents directly, which occurs when the request mode is set to `no-cors`. However, this mode severely limits what you can do with the response and is often not a practical solution.

### Solutions:

1. **Enable CORS on the server**:
   - The most reliable way to fix this is to modify the server (the one serving the image) to include the appropriate CORS headers.
   - The server needs to send a response header like:
     ```
     Access-Control-Allow-Origin: *
     ```
     or
     ```
     Access-Control-Allow-Origin: http://localhost:8080
     ```
     This header allows the resource to be accessed from the specified origin (your localhost in this case).

2. **Proxy the Request**:
   - If you can't modify the server, you can set up a proxy server that your application will contact instead. The proxy would make the request to the resource, bypassing the CORS restrictions, and send the data back to your application.

3. **Set the Fetch Mode to `no-cors` (Limited Use Case)**:
   - You could set the `mode` of your fetch request to `no-cors`, but this will give you an "opaque response", meaning that you won't be able to access the contents of the response directly (e.g., the image data). This solution works only for certain use cases where you don’t need to interact with the response.
   ```javascript
   fetch('https://s.....5524408624459885.jpg', {
       mode: 'no-cors'
   })
   ```
   **Note**: This solution is limited, and you won’t have access to the actual image data.

4. **Use a CORS Proxy**:
   - You can use services like [cors-anywhere](https://cors-anywhere.herokuapp.com/) that act as a proxy to bypass CORS restrictions. Just prepend the CORS proxy URL to your request.
   ```
   https://cors-anywhere.herokuapp.com/https://s.....5524408624459885.jpg
   ```
