### ISSUE TITLE
Issues with the landscapist-bom package - missing coil3 / cannot use platform()

### ISSUE THREAD

**Issue by kroegerama** [skydoves/landscapist#630]
Hi! I just realized that you also provide a bom immediately tried to use it. Unfortunately, there are currently two issues with it:

1. The bom is missing `landscapist-coil3`
2. The [bom artifact](https://repo1.maven.org/maven2/com/github/skydoves/landscapist-bom/2.4.4/landscapist-bom-2.4.4.pom) is missing `<packaging>pom</packaging>` and there is also a jar, which is unnecessary.
The default way of importing a bom `implementation(platform("com.github.skydoves:landscapist-bom:2.4.4"))` does not work here.
You can find an example of a correctly working bom artifact in the [coil maven repo](https://repo1.maven.org/maven2/io/coil-kt/coil3/coil-bom/3.0.4/coil-bom-3.0.4.pom)

Nevertheless, this is a great library. Thanks for all the great work 🙂

**Comment by skydoves** [comment]
Hey @kroegerama, a new version 2.4.5 has been released and coil3 is available with the bom package. Thank you for raising this issue!
