### ISSUE TITLE
[Suggestion] Mark dependency version in document or release note

### ISSUE THREAD

**Issue by WadeXHong** [skydoves/Landscapist#67]
When I used Landscapist with Glide in my present project for the first time, I run into a start up crash thrown by Glide with little information. Finally I found out it might cause by the minor different dependency version of Glide between project and library (4.9.0 vs 4.12.0).
Maybe it's better to put dependency version in README or just tell user to find it in `dependencies.gradle` by themselves :).

**Comment by skydoves** [comment]
Hi @WadeXHong,
That's a great point. I will update README including the libraries' dependency versions.
Thanks!
