### ISSUE TITLE
No static method FrescoImage

### ISSUE THREAD

**Issue by tannotour** [skydoves/Landscapist#8]
i write it according to doc, 

FrescoImage(
            imageUrl = "https://www.google.com.tw/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png",
            contentScale = ContentScale.Crop
)

but got a "java.lang.NoSuchMethodError: No static method FrescoImage" error.
detail:
java.lang.NoSuchMethodError: No static method FrescoImage(Ljava/lang/String;Lcom/facebook/imagepipeline/request/ImageRequest;Landroidx/compose/ui/Modifier;Landroidx/compose/ui/Alignment;Landroidx/compose/ui/layout/ContentScale;FLandroidx/compose/ui/graphics/ColorFilter;ZILandroidx/compose/ui/graphics/ImageAsset;Landroidx/compose/ui/graphics/ImageAsset;ZLandroidx/compose/runtime/Composer;II)V in class Lcom/skydoves/landscapist/fresco/FrescoImage; or its super classes

**Comment by skydoves** [comment]
Hi, @tannotour.
Which version do you use?
In my project, `landscapist-1.1.0` and `compose-1.0.0-alpha07` work fine for me.

**Comment by tannotour** [comment]
> Hi, @tannotour.
> Which version do you use?
> In my project, `landscapist-1.1.0` and `compose-1.0.0-alpha07` work fine for me.

Hi，@skydoves.
now use compose-1.0.0-alpha07 work fine, thanks. 
I used version compose-1.0.0-alpha04 yesterday and it does not work, It seems that it may be a problem with compose-1.0.0-alpha04.
