### ISSUE TITLE
Local drawables proportion not remaining intact

### ISSUE THREAD

**Issue by shubhampatel-hotstar** [skydoves/Landscapist#84]
**Please complete the following information:**
- Library Version [e.g. v1.0.0] v1.3.6
- Affected Device(s) [e.g. Samsung Galaxy s10 with Android 9.0] Android 11
 
**Describe the Bug:**

While using `CoilImage` with the local drawable resource, the image is becoming bigger than its actual proportions. Also while passing the resource as a `painterResource(R.drawable.sample)` the same thing happening.

**Expected Behavior:**

The drawable resource should rather visualise with its actual proportions.

**Comment by skydoves** [comment]
The sizes depend on the parent's layout size.
Could you build with this code?
```kotlin
Box(modifier = Modifier.width(30.dp)) {

 CoilImage(..)
}
```

**Comment by shubhampatel-hotstar** [comment]
Now I am unable to see the bitmap itself. Here is the composable that I am using - 
`
@Composable
fun Title() {
    Box(modifier = Modifier.width(312.dp).height(100.dp)) {
        CoilImage(
            imageModel = R.drawable.sample_title_image,
            contentDescription = "movie"
        )
    }
}
`

**Comment by skydoves** [comment]
I guess one thing is missing:

```kotlin
modifier = Modifier.size(50.dp)
```

**Comment by skydoves** [comment]
Will close this issue.
Please reopen if you get the same issue again. :)
