### ISSUE TITLE
Images not loading after started using compose 1.0.0-alpha08

### ISSUE THREAD

**Issue by miduch** [skydoves/Landscapist#9]
- Library Version:  v1.1.1
- Pixel 4, Emulator 
 
Images not loading anymore after started to use compose 1.0.0-alpha08, i have a CircularProgressIndicator set for loading {} 
only that one is shown. No actual is loaded from provided url 

**Expected Behavior:**

Images can be loaded

**Comment by skydoves** [comment]
Hi, @miduch 
I just build the [demo project](https://github.com/skydoves/disneycompose), but It works fine to me.
Could you test using the demo project?

**Comment by skydoves** [comment]
I used this code:
```kotlin
@Composable
fun NetworkImage(
  url: String,
  modifier: Modifier,
  circularRevealedEnabled: Boolean = false,
  contentScale: ContentScale = ContentScale.Crop
) {
  CoilImage(
    imageModel = url,
    modifier = modifier,
    contentScale = contentScale,
    circularRevealedEnabled = circularRevealedEnabled,
    circularRevealedDuration = 450,
    loading = {
      ConstraintLayout(
        modifier = Modifier.fillMaxSize()
      ) {
        val indicator = createRef()
        CircularProgressIndicator(
          modifier = Modifier.constrainAs(indicator) {
            top.linkTo(parent.top)
            bottom.linkTo(parent.bottom)
            start.linkTo(parent.start)
            end.linkTo(parent.end)
          }
        )
      }
    },
    failure = {
      Text(
        text = "image request failed.",
        style = MaterialTheme.typography.body2
      )
    }
  )
}
```

**Comment by miduch** [comment]
CoilImage otherwise seems to be working fine in test @Composable but in my actual use case it just doesn't get updated with fetched images and those spinners keep animating. urls are fine i checked

**Comment by skydoves** [comment]
Could you give me some examples? I will check the problem.

**Comment by miduch** [comment]
sorry for delay, actually it started to work correctly after i reinstalled app -> closed issue after that
