### ISSUE TITLE
Doubled offset from Modifier.offset()

### ISSUE THREAD

**Issue by NazarDunets** [skydoves/Landscapist#92]
Info:
- landscapist-glide:1.3.7
- Pixel 4a API 31 (physical). Pixel 2 API 29 (emulator)
 
Bug:

When using Modifier.offset(), actual image is located in position offsetVariable * 2. If I set background with Modifier.background, it is located in correct position, while image is not. Problem is not related to offset calculation on my side, any other composable works fine.

Expected Behavior:

Image is located in correct position.

https://user-images.githubusercontent.com/75180459/143863509-3e1e56c0-0db2-41e6-8664-5d2810547919.mov

https://user-images.githubusercontent.com/75180459/143863529-9cadc78a-c888-4dc7-8770-7591d31c084c.mov

**Comment by skydoves** [comment]
Hey @NazarDunets,
Is the same result if you build with the recent version `1.4.3`?

**Comment by NazarDunets** [comment]
Should've checked that in the first place. Works as intended with 1.4.3.
