### ISSUE TITLE
Coil VideoFrame ComponentRegistry Not Working

### ISSUE THREAD

**Issue by jschleppy** [skydoves/landscapist#98]
- Library Version 1.4.5
- Affected Device(s) all
 
I'm trying to use Coil feature to load video thumbnails, but can't get it to work. Following documentation [seen here](https://coil-kt.github.io/coil/videos/), I have added the dependency, then registered the three video frame component's to the ImageLoader passed into CoilImage. 

Additionally, since I don't have access to the load function, I can't edit videoFrameMillis either to customize which frame gets chosen.

Since I can access the Coil image loader, I would've expected these to work. Any thoughts on why they may not be?

**Comment by skydoves** [comment]
Hey @jschleppy, sorry for the late response. Landscapist doesn't support the feature, which plays a video for now. I'll consider supporting this in the future. Anyway thanks for reporting this issue!

**Comment by skydoves** [comment]
I'm closing this issue now because I don't have plans yet for supporting this.

**Comment by jschleppy** [comment]
All good, thanks for considering it. I landed on using Coil directly so this is no longer needed by me.
